#!/usr/bin/expect
set timeout 10
spawn scp /usr/src/packages/RPMS/i586/fileserver-1.0-1.i586.rpm root@192.168.1.10:/srv/www/
expect "*password*"
send "111111\r"
spawn ssh root@192.168.1.10
expect "*password*"
send "111111\r"
expect "#"
send "cp -r /srv/www/fileserver-1.0-1.i586.rpm /srv/\r"
expect eof

