#!/bin/sh

cleanup()
{
	echo "cleaning up ..."
	exit 20
}

exec_ssh()
{
	IP=$1
	PASSWD=$2
	COMM=$3
	
	expect -c "
		set timeout -1
		spawn ssh root@$IP $COMM
		expect \"(yes/no)?\" {
			send \"yes\r\"
			expect \"Password:\"
				send \"$PASSWD\r\"
		} \"Password:\" {
			send \"$PASSWD\r\"
		} eof {
			exit
		}
		expect eof
		exit
	"
}

exec_scp()
{
	S_FILE=$1
	IP=$2
	PASSWD=$3
	D_FILE=$4
	
	expect -c "
		set timeout -1
		spawn scp -r $S_FILE root@$IP:$D_FILE
		expect \"(yes/no)?\" {
			send \"yes\r\"
			expect \"Password:\"
				send \"$PASSWD\r\"
		} \"Password:\" {
			send \"$PASSWD\r\"
		} eof {
			exit
		}
		expect eof
		exit
	"
}

