#!/bin/sh

DISTRO_DIR=/cscloud_distro
DISTRO_TARFILE=cscloud-1.0.tar.gz

cleanup()
{
	echo "cleaning up ..."
	rm -rf $DISTRO_DIR
	exit 20
}

# If interrupted, clean up
trap cleanup 2 3

# Check user
id | grep "uid=0(" > /dev/null
if [ $? != "0" ]; then
	echo "ERROR: This script requires root to run."
	exit 1
fi

# Check path
pwd | grep "scripts" > /dev/null
if [ $? != "0" ]; then
	echo "ERROR: This script needs to run under its directory."
	exit 1
fi

echo "Preparing software package ..."
mkdir -p $DISTRO_DIR/cscloud/src/1.0
#/bin/cp -dpR ../../* $DISTRO_DIR/cscloud/src/1.0 > /dev/null 2>&1
/bin/cp -dpR ../../{configmanager,managerserver,fileserver} $DISTRO_DIR/cscloud/src/1.0 > /dev/null 2>&1
if [ $? != "0" ]; then
	echo "ERROR: Copying files failed."
	cleanup
fi

cd $DISTRO_DIR
rm cscloud/src/1.0/configmanager/scripts/csc_prepareDistro
find . -type d -name ".svn" | xargs rm -rf
mv cscloud/src/1.0/configmanager/scripts/csc_admin_install.sh .
tar -p --same-owner -zcvf $DISTRO_TARFILE ./cscloud > /dev/null && rm -rf ./cscloud
if [ $? != "0" ]; then
	echo "ERROR: Packaging files failed."
	cleanup
fi

echo "Distro package ready for copying and installing on admin node."

exit 0


